---
# The default location for Konsole config files is:
#   "{{ ansible_env.HOME }}/.kde/share/apps/konsole"
# Check there for pristine copies. These tasks write to:
#   "{{ ansible_env.HOME }}/.local/share/konsole"
#   "{{ ansible_env.HOME }}/.config"
# to override the pristine versions.
- name: Create local Konsole config directory.
  file:
    state: directory
    path: "~{{ konsole_username }}/.local/share/konsole"

# Configures Konsole dotfiles
- name: Copy konsolerc.
  template:
    src: konsolerc.j2
    dest: "~{{ konsole_username }}/.config/konsolerc"

- name: Copy default Konsole profile.
  template:
    src: Shell.profile.j2
    dest: "~{{ konsole_username }}/.local/share/konsole/Shell.profile"

- name: Copy custom Konsole color scheme.
  copy:
    src: Linux.colorscheme
    dest: "~{{ konsole_username }}/.local/share/konsole/Linux.colorscheme"
  when: konsole_configure_colorscheme is defined and
        konsole_configure_colorscheme == true
