---
# TODO: Figure out the correct config directories, because
# the tasks below write to .kde and .local. That can't be right.
- name: Create local Konsole config directory.
  file:
    state: directory
    path: "~{{ username }}/.local/share/konsole"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Create Konsole config directories.
  file:
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"
    path: "~{{ username }}/.kde/share/{{ item }}"
  with_items:
    - config
    - apps/konsole

# Configures Konsole dotfiles
- name: Copy konsolerc.
  copy:
    src: konsolerc
    dest: "~{{ username }}/.kde/share/config/konsolerc"

- name: Copy default Konsole profile.
  copy:
    src: Shell.profile
    dest: "~{{ username }}/.kde/share/apps/konsole/Shell.profile"

- name: Copy custom Konsole color scheme.
  copy:
    src: Linux.colorscheme
    # Default location is here, and has a pristine copy.
    # dest: "~{{ username }}/.kde/share/apps/konsole/Linux.colorscheme"
    # Custom location, overrides the default.
    dest: "~{{ username }}/.local/share/konsole/Linux.colorscheme"
  when: konsole_custom_color is defined and
        konsole_custom_color == true
